# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-05 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import tweet.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0004_tweet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=140, validators=[tweet.models.validate_content]),
        ),
    ]
